### ISSUE TITLE
request: Better Dockerfile!

### ISSUE THREAD

**Issue by youKnowOwO** [youKnowOwO/yumeko#37]
Just lack knowledge about docker. I think my dockerfile isn't efficient and bad for production.

**Comment by Hazmi35** [comment]
I could do this, how do you want it to be?

**Comment by youKnowOwO** [comment]
To be honest idk how to explain. Maybe avoiding yarn clean cache is good for installing dependencies faster :/ ?

**Comment by youKnowOwO** [comment]
Also I don't know which package is used only once to build the image and which package is really needed for the process to run.

**Comment by Hazmi35** [comment]
Do you want multi-staged Dockerfile?
